[[redirects]]
	from = "/en/*"
	to = "/en/404/"
	status = 404

[[redirects]]
	from = "/cs/*"
	to = "/cs/404/"
	status = 404

[[redirects]]
	from = "/*"
	to = "/en/404/"
	status = 404

[[redirects]]
	from = "/zpevnik"
	to = "/cs/song-book/"
	status = 200
